---
- name: Get show running-config
  hosts: routers
  gather_facts: no
  connection: network_cli        # ใช้ SSH แล้วเข้าสู่ privileged exec ของ Cisco
  collections:
    - cisco.ios                 # บอกว่าใช้ collection นี้โดยตรง

  tasks:
    - name: Run show running-config
      ios_command:              # ใช้ ios_command แทน cisco.ios.ios_command ได้เลย
        commands:
          - show running-config
        wait_for:
          - result[0] contains "end"    # บังคับให้รอจนกว่าคำว่า 'end' ปรากฏ
        retries: 30                     # รอสูงสุด ~30 รอบ
        interval: 5    
      register: runout

    - name: Save to local file
      delegate_to: localhost
      copy:
        content: "{{ runout.stdout[0] }}"
        dest: "./show_run_{{ lookup('env','STUDENT_ID') | default('66070052') }}_CSR1KV.txt"
